# langage du test
language: python
# version
python:
  - 3.8
# on lance le script de test
script:
  - python3 -m spacy download fr_core_news_md
  - pytest --count=500 -v -s test.py
# notifications par email
notifications:
  email:
    recipients:
      - victor.meynaud@chartes.psl.eu
    on_success: never
    on_failure: never